Repository withmartian/llm-adapters, pull requests merged in 2025-02, with the labels that each got.

#146 Add deepseek provider
  adapters/provider_adapters/__init__.py
  adapters/provider_adapters/deepseek_sdk_chat_provider_adapter.py
  adapters/types.py
  pyproject.toml
  tests/adapters/assistant/cassettes/test_assistant_first/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/assistant/cassettes/test_assistant_first/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/assistant/cassettes/test_assistant_last/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/assistant/cassettes/test_assistant_last/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/assistant/cassettes/test_assistant_only/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/assistant/cassettes/test_assistant_only/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/assistant/cassettes/test_assistant_repeating/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/assistant/cassettes/test_assistant_repeating/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_empty_content/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_empty_content/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_max_completion_tokens/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_max_completion_tokens/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_max_tokens/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_max_tokens/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_min_p/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_min_p/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_stop/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_stop/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_stop/test_async_list[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_stop/test_async_list[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_stream/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_stream/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_stream/test_sync[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_stream/test_sync[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_temperature/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_temperature/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_top_k/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_top_k/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_top_p/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_top_p/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_user_only/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_user_only/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_user_only_conversation/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_user_only_conversation/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/cassettes/test_user_repeating/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/cassettes/test_user_repeating/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/json/cassettes/test_json_content/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/json/cassettes/test_json_content/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/json/cassettes/test_json_output/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/system/cassettes/test_system_last/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/system/cassettes/test_system_last/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/system/cassettes/test_system_only/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/system/cassettes/test_system_only/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/system/cassettes/test_system_repeating/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/system/cassettes/test_system_repeating/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/tools/cassettes/test_tools/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/tools/cassettes/test_tools_choices/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/tools/cassettes/test_tools_choices_none/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/adapters/tools/cassettes/test_tools_choices_none/test_async[deepseek-deepseek-deepseek-reasoner].yaml
  tests/adapters/tools/cassettes/test_tools_choices_required/test_async[deepseek-deepseek-deepseek-chat].yaml
  tests/utils.py
Labels: enhancement, size:XXL, lgtm

#147 fix typo in README
  README.md
Labels: documentation, size:XS, lgtm

#150 feat: add gpt 4.5
  adapters/provider_adapters/openai_sdk_chat_provider_adapter.py
  pyproject.toml
  tests/adapters/assistant/cassettes/test_assistant_first/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/assistant/cassettes/test_assistant_first/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/assistant/cassettes/test_assistant_last/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/assistant/cassettes/test_assistant_last/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/assistant/cassettes/test_assistant_only/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/assistant/cassettes/test_assistant_only/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/assistant/cassettes/test_assistant_repeating/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/assistant/cassettes/test_assistant_repeating/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_empty_content/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_empty_content/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_max_completion_tokens/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_max_completion_tokens/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_max_tokens/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_max_tokens/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_min_p/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_min_p/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_n/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_n/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_stop/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_stop/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_stop/test_async_list[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_stop/test_async_list[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_stream/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_stream/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_stream/test_sync[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_stream/test_sync[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_temperature/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_temperature/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_top_k/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_top_k/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_top_p/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_top_p/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_user_only/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_user_only/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_user_only_conversation/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_user_only_conversation/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_user_repeating/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_user_repeating/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/cassettes/test_vision/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/cassettes/test_vision/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/json/cassettes/test_json_content/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/json/cassettes/test_json_content/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/json/cassettes/test_json_output/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/json/cassettes/test_json_output/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/system/cassettes/test_system_last/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/system/cassettes/test_system_last/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/system/cassettes/test_system_only/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/system/cassettes/test_system_only/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/system/cassettes/test_system_repeating/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/system/cassettes/test_system_repeating/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/tools/cassettes/test_tools/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/tools/cassettes/test_tools/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/tools/cassettes/test_tools_choices/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/tools/cassettes/test_tools_choices/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/tools/cassettes/test_tools_choices_none/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/tools/cassettes/test_tools_choices_none/test_async[openai-openai-gpt-4.5-preview].yaml
  tests/adapters/tools/cassettes/test_tools_choices_required/test_async[openai-openai-gpt-4.5-preview-2025-02-27].yaml
  tests/adapters/tools/cassettes/test_tools_choices_required/test_async[openai-openai-gpt-4.5-preview].yaml
Labels: size:XXL, lgtm
