Repository withmartian/llm-adapters, pull requests merged in 2025-01, with the labels that each got.

#140 chore: upgrade packages
  .pre-commit-config.yaml
  adapters/provider_adapters/anthropic_sdk_chat_provider_adapter.py
  adapters/provider_adapters/openai_sdk_chat_provider_adapter.py
  adapters/types.py
  poetry.lock
  pyproject.toml
Labels: size:M, lgtm

#141 feat: add support for extra body, headers and query
  adapters/abstract_adapters/sdk_chat_adapter.py
  pyproject.toml
Labels: enhancement, size:S, lgtm

#144 Bump library version
  pyproject.toml
Labels: size:XS, lgtm

#145 add yml for version check github action
  .github/workflows/version-check.yml
  pyproject.toml
Labels: enhancement, size:M, lgtm
